version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ollama
    environment:
      - DATABASE_URL=postgres://athena:athena_pass@db:5432/athenadb
      - OLLAMA_HOST=http://ollama:11434
      - GEMINI_API_KEy=AIzaSyDitgqAYjD9155bOXU6J5ayCbEKotnDcIw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=athena
      - POSTGRES_PASSWORD=athena_pass
      - POSTGRES_DB=athenadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

volumes:
  postgres_data:
  ollama_data:
