name: Cloud Forge Zig
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Zig & Cargo-Zigbuild
        run: |
          sudo snap install zig --classic --beta
          cargo install cargo-zigbuild
      - name: Build for Android (ARM64)
        run: |
          rustup target add aarch64-linux-android
          cargo zigbuild --release --target aarch64-linux-android
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexus-bin-zig
          path: "target/aarch64-linux-android/release/nexus_singularity"
